Fixed binutils pass 1

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,6 +1,54 @@
 #!/bin/bash
 
+# Verifies the working of GCC compiler and linker
+testToolchain () {
+    echo 'int main(){}' > dummy.c && gcc -o dummy dummy.c
+    TCT=$(readelf -l dummy | grep ': /tools')
+    displayMsg OK "Toolchain Test: "
+    if [ -n "$TCT" ]
+    then
+        displayMsg OK "$TCT"
+        displayMsg OK "Successful"
+        rm dummy.c dummy
+    else 
+        displayMsg ERR "Failed"
+        exit 1;
+    fi
+}
+
 # Silence wget
 wget() {
     $(which wget) --no-check-certificate $@ 2> /dev/null
+}
+
+# Extracts source code for the selected package.
+extractPkg() {
+    if [ "$(echo ${2} | grep "BASIC")" ]
+    then
+        EXTRACT_DIR="${MOUNT_POINT}${PKG_BASIC_DIR}"
+    else
+        EXTRACT_DIR="${MOUNT_POINT}${PKG_STD_DIR}"
+    fi
+    # Extract the primary source archive to a new directory.
+    if [ "$(echo ${1} | grep \\.zip\$)" ]
+    then
+        displayMsg OK "... Extracting source code"
+        unzip "${EXTRACT_DIR}/${1}" -d "${EXTRACT_DIR}"
+    elif [ "$(isArchive ${1})" ]
+    then
+        displayMsg OK "... Extracting source code"
+        tar xf "${EXTRACT_DIR}/${1}" -C "${EXTRACT_DIR}"
+    else
+            displayMsg ERR "... Unknown source format. Not extracting '${1}'"
+    fi
+}
+
+# Checks if a filename is an archive that can be extracted.
+isArchive() {
+  for ext in \\.zip \\.tar\\.bz2 \\.tar\\.gz \\.tar\\.xz \\.tgz \\.tar; do
+    if [ "$(echo ${1} | grep ${ext}\$)" ]; then
+      echo "true"
+      return
+    fi
+  done
 }
