Update

diff --git a/getPkgs b/getPkgs
--- a/getPkgs
+++ b/getPkgs
@@ -1,38 +1,35 @@
 #!/bin/bash
 
-getBasicPkgs() {
-    displayMsg OK "Verifying packages ..."
-    cd $MOUNT_POINT
+source handleErrors
+source global
+
+displayMsg OK "Verifying packages ..."
     
-    # Change to the package directory
-    if [ ! -d $PKG_BASIC_DIR ]
+# Change to the package directory
+if [ ! -d $PKG_BASIC_DIR ]
+then
+    mkdir -p $PKG_BASIC_DIR
+fi
+    
+cd $PKG_BASIC_DIR
+if [ $(ls -l | wc -l) != 81 ]
+then
+    displayMsg OK "Downloading packages ..."
+    wget --continue --input-file="../../../${WGET_LIST_BASIC}" || $ERR=$?
+        
+    if [ "${ERR}" = "127" ]
     then
-        mkdir -p $PKG_BASIC_DIR
+        displayMsg ERR "You do not have the 'wget' utility installed."
+        displayMsg ERR "Therefore you should download all the required"
+        displayMsg ERR "sources manually... Or install 'wget'."
+        exit 1
+    elif [ "${ERR}" != "" ]; then
+        displayMsg ERR "Primary URL is down. Please try againg later."
+        exit 1
     fi
-    
-    cd $PKG_BASIC_DIR
-    if [ $(ls -l | wc -l) != 81 ]
-    then
-        displayMsg OK "Downloading packages ..."
-        sudo wget --continue --input-file="../../../${WGET_LIST_BASIC}" || $ERR=$?
         
-        if [ "${ERR}" = "127" ]
-        then
-            displayMsg ERR "You do not have the 'wget' utility installed."
-            displayMsg ERR "Therefore you should download all the required"
-            displayMsg ERR "sources manually... Or install 'wget'."
-            exit 1
-        elif [ "${ERR}" != "" ]; then
-            displayMsg ERR "Primary URL is down. Please try againg later."
-            exit 1
-        fi
-        
-        # Remove wget logs
-        sudo rm wget-log*
-        # Change directory to home
-        cd ../../../
-        # Copy the data to the mount point
-        cp -ur ./* $MOUNT_POINT
+    # Remove wget logs
+    rm wget-log*
     fi
 }
 
